# Generated by Django 5.1.2 on 2024-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Girasol',
            fields=[
                ('Id_girasol', models.AutoField(primary_key=True, serialize=False)),
                ('Año_girasol', models.IntegerField()),
                ('Provincia_girasol', models.TextField()),
                ('Departamento_girasol', models.TextField()),
                ('Superficie_sembrada_girasol', models.BigIntegerField(help_text='Superficie sembrada en hectáreas')),
                ('Superficie_cosechada_girasol', models.BigIntegerField(help_text='Superficie cosechada en hectáreas')),
                ('Produccion_girasol', models.BigIntegerField(help_text='Producción en toneladas')),
                ('Rendimiento_girasol', models.FloatField(help_text='Rendimiento en Kg/ha')),
            ],
            options={
                'db_table': 'girasol',
            },
        ),
        migrations.CreateModel(
            name='Maiz',
            fields=[
                ('Id_maiz', models.AutoField(primary_key=True, serialize=False)),
                ('Año_maiz', models.IntegerField()),
                ('Provincia_maiz', models.TextField()),
                ('Departamento_maiz', models.TextField()),
                ('Superficie_sembrada_maiz', models.BigIntegerField(help_text='Superficie sembrada en hectáreas')),
                ('Superficie_cosechada_maiz', models.BigIntegerField(help_text='Superficie cosechada en hectáreas')),
                ('Produccion_maiz', models.BigIntegerField(help_text='Producción en toneladas')),
                ('Rendimiento_maiz', models.FloatField(help_text='Rendimiento en Kg/ha')),
            ],
            options={
                'db_table': 'maiz',
            },
        ),
        migrations.CreateModel(
            name='Soja',
            fields=[
                ('Id_soja', models.AutoField(primary_key=True, serialize=False)),
                ('Año_soja', models.IntegerField()),
                ('Provincia_soja', models.TextField()),
                ('Departamento_soja', models.TextField()),
                ('Superficie_sembrada_soja', models.BigIntegerField(help_text='Superficie sembrada en hectáreas')),
                ('Superficie_cosechada_soja', models.BigIntegerField(help_text='Superficie cosechada en hectáreas')),
                ('Produccion_soja', models.BigIntegerField(help_text='Producción en toneladas')),
                ('Rendimiento_soja', models.FloatField(help_text='Rendimiento en Kg/ha')),
            ],
            options={
                'db_table': 'soja',
            },
        ),
    ]
